import React from 'react';

const sectionTitle = { color: 'var(--text-primary)', fontSize: '24px', marginBottom: '16px', marginTop: '40px' };
const list = { marginLeft: '24px', marginTop: '12px' };
const spacer = { marginTop: '12px' };

const TermsPage = () => {
  return (
    <>
      <section className="mkt-hero" style={{ paddingBottom: '40px' }}>
        <div className="mkt-container">
          <h1 className="mkt-hero-title" style={{ fontSize: '40px' }}>Terms of Service</h1>
          <p className="mkt-hero-subtitle">Effective date: March 26, 2026</p>
        </div>
      </section>

      <section className="mkt-section" style={{ paddingTop: 0 }}>
        <div className="mkt-container" style={{ maxWidth: '800px' }}>
          <div style={{ color: 'var(--text-secondary)', lineHeight: '1.8', fontSize: '15px' }}>

            <p>These Terms of Service ("Terms") govern your access to and use of the AdgrowAI platform operated by AdgrowAI ("we," "our," or "us") at <a href="https://www.adgrowai.com" style={{ color: 'var(--blue-primary)' }}>www.adgrowai.com</a> and <a href="https://app.adgrowai.com" style={{ color: 'var(--blue-primary)' }}>app.adgrowai.com</a>. By using our services, you agree to these Terms.</p>

            <h2 style={sectionTitle}>1. Description of Service</h2>
            <p>AdgrowAI is an AI-powered advertising optimization platform designed for small and medium-sized businesses. We provide Google Ads and Meta Ads campaign analysis, insights, recommendations, and execution tools.</p>
            <div style={{
              background: 'rgba(76, 111, 255, 0.08)',
              borderLeft: '3px solid var(--blue-primary)',
              padding: '20px 24px',
              borderRadius: '0 8px 8px 0',
              margin: '16px 0'
            }}>
              <p><strong style={{ color: 'var(--text-primary)' }}>AI explains, never decides.</strong> All optimization recommendations generated by AdgrowAI require your explicit review and approval before any changes are made to your advertising accounts.</p>
            </div>

            <h2 style={sectionTitle}>2. Account Registration</h2>
            <p>To use AdgrowAI, you must:</p>
            <ul style={list}>
              <li>Create an account with a valid email address and password.</li>
              <li>Maintain the confidentiality of your account credentials.</li>
              <li>Be responsible for all activities that occur under your account.</li>
              <li>Notify us immediately of any unauthorized use of your account.</li>
              <li>Be at least 18 years of age.</li>
            </ul>

            <h2 style={sectionTitle}>3. Connecting Advertising Accounts</h2>
            <p>By connecting your advertising accounts, you:</p>
            <ul style={list}>
              <li>Authorize AdgrowAI to access your campaign data through the respective platform APIs.</li>
              <li>Acknowledge that AdgrowAI will only make changes to your campaigns after your explicit approval of each recommendation.</li>
              <li>May disconnect your advertising accounts at any time through your account settings.</li>
              <li>Are solely responsible for ensuring you have the authority to connect and manage the linked advertising accounts.</li>
            </ul>

            <h2 style={sectionTitle}>4. Subscription and Payment</h2>
            <ul style={list}>
              <li>AdgrowAI offers paid subscription plans.</li>
              <li>Subscriptions are billed on a recurring basis unless cancelled.</li>
              <li>We reserve the right to modify pricing with reasonable notice.</li>
            </ul>

            <h2 style={sectionTitle}>5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul style={list}>
              <li>Use AdgrowAI for any unlawful purpose or in violation of applicable laws.</li>
              <li>Attempt to gain unauthorized access to any part of the platform or its systems.</li>
              <li>Interfere with or disrupt the service or its servers.</li>
              <li>Reverse engineer, decompile, or disassemble any part of the service.</li>
              <li>Send spam or unsolicited communications through the platform.</li>
              <li>Share your account credentials with third parties.</li>
              <li>Use automated tools to scrape or extract data from the platform.</li>
            </ul>

            <h2 style={sectionTitle}>6. Intellectual Property</h2>
            <p>The AdgrowAI platform, including its software, design, algorithms, content, and branding, is owned by AdgrowAI and protected by intellectual property laws. We grant you a limited, non-exclusive, non-transferable license to use the platform during your active subscription.</p>
            <p style={spacer}>You retain full ownership of all your data, including advertising account data and business information you provide.</p>

            <h2 style={sectionTitle}>7. Disclaimer of Warranties</h2>
            <p>AdgrowAI is provided on an "as is" and "as available" basis without warranties of any kind, express or implied. We do not guarantee uninterrupted or error-free service.</p>
            <p style={spacer}>We do not guarantee specific advertising results. Our recommendations are based on data analysis and best practices, but outcomes depend on many factors beyond our control, including market conditions, competition, and platform algorithm changes. No specific return on investment, cost reduction, or performance improvement is guaranteed.</p>

            <h2 style={sectionTitle}>8. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law:</p>
            <ul style={list}>
              <li>AdgrowAI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities.</li>
              <li>Our total aggregate liability shall not exceed the amount you paid to AdgrowAI in the 12 months preceding the claim.</li>
            </ul>

            <h2 style={sectionTitle}>9. Indemnification</h2>
            <p>You agree to indemnify and hold harmless AdgrowAI, its officers, employees, and agents from any claims, damages, losses, liabilities, and expenses (including reasonable attorney's fees) arising from your use of the service, violation of these Terms, or infringement of any third-party rights.</p>

            <h2 style={sectionTitle}>10. Termination</h2>
            <ul style={list}>
              <li><strong style={{ color: 'var(--text-primary)' }}>By you:</strong> You may cancel your account at any time through your account settings or by contacting us.</li>
              <li><strong style={{ color: 'var(--text-primary)' }}>By us:</strong> We may suspend or terminate your access if you violate these Terms.</li>
            </ul>
            <p style={spacer}>Upon termination, your right to use the platform ceases immediately. We may retain certain data as required by law.</p>

            <h2 style={sectionTitle}>11. Modifications to Terms</h2>
            <p>We may update these Terms from time to time. Material changes will be communicated by email or through the platform. Continued use of the service after changes constitutes acceptance of the revised Terms.</p>

            <h2 style={sectionTitle}>12. Governing Law</h2>
            <p>These Terms are governed by the laws of New Zealand. In the event of a dispute, both parties agree to first attempt resolution through good-faith negotiation. If negotiation fails, disputes shall be resolved through the courts of New Zealand.</p>

            <h2 style={sectionTitle}>13. Contact Us</h2>
            <p>If you have questions about these Terms, contact us at:</p>
            <p style={spacer}><strong style={{ color: 'var(--text-primary)' }}>AdgrowAI Limited</strong></p>
            <p>NZ Company No. 9418222 | NZBN 9429053564504</p>
            <p>Registered office: 117 Wiseley Road, West Harbour, Auckland 0618, New Zealand</p>
            <p>Email: <a href="mailto:admin@adgrowai.com" style={{ color: 'var(--blue-primary)' }}>admin@adgrowai.com</a></p>
            <p>Website: <a href="https://www.adgrowai.com" style={{ color: 'var(--blue-primary)' }}>www.adgrowai.com</a></p>
          </div>
        </div>
      </section>
    </>
  );
};

export default TermsPage;
